site_name: Faust Language
site_description: A guide to the Faust Programming Language.
copyright: Copyright &copy; 2020 <a href="http://www.grame.fr">Grame-CNCM</a>
nav:
    - Home: index.md
    - User Guide: 
        - 'Introduction' : guide/introduction.md
        - 'Quick start':   guide/quick-start.md
        - 'Embedding':     guide/embedding.md
        - 'OSC Support':   guide/osc.md
        - 'HTTP Support':  guide/http.md
        - 'MIDI Support':  guide/midi.md
        - 'Math. Doc':     guide/mathdoc.md
    - Reference: 
        - 'Faust Syntax':       refs/syntax.md
        - 'Compiler Options':   refs/options.md
        - 'Using the Compiler': refs/compiler.md
        - 'Using Tools':        refs/tools.md
    - Examples: 
         - ' ambisonics ':  examples/ambisonics.md
         - ' analysis ':  examples/analysis.md
         - ' bela ':  examples/bela.md
         - ' delayEcho ':  examples/delayEcho.md
         - ' dynamic ':  examples/dynamic.md
         - ' filtering ':  examples/filtering.md
         - ' gameaudio ':  examples/gameaudio.md
         - ' generator ':  examples/generator.md
         - ' misc ':  examples/misc.md
         - ' phasing ':  examples/phasing.md
         - ' physicalModeling ':  examples/physicalModeling.md
         - ' pitchShifting ':  examples/pitchShifting.md
         - ' psychoacoustic ':  examples/psychoacoustic.md
         - ' reverb ':  examples/reverb.md
         - ' SAM ':  examples/SAM.md
         - ' smartKeyboard ':  examples/smartKeyboard.md
         - ' spat ':  examples/spat.md
         - ' Download examples ':  rsrc/examples.zip
    - About: about.md

#theme: readthedocs

site_dir: ../docs


extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/faustdoc
        - type: home
          link: https://faust.grame.fr
        - type: envelope
          link: mailto:orlarey@grame.fr

plugins:
    - search
    - pdf-export:
          verbose: false
          media_type: print
          combined: true
          combined_output_path: Faust-Documentation.pdf
          enabled_if_env: ENABLE_PDF_EXPORT

extra_css:
   - '/css/faust.css'

markdown_extensions:
    - markdown_include.include:
        base_path: './docs'
